version: "3"
services:
  app:
    container_name: dev_rails_vue_sample_app
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    networks:
      - dev_rails_vue_sample_network
  db:
    container_name: dev_rails_vue_sample_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "33369:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - dev_rails_vue_sample_network

volumes:
  mysql_volume:

networks:
  dev_rails_vue_sample_network:
