version: "3"
services:
  app:
    container_name: dev_rails_vue_sample_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - db
    networks:
      - dev_rails_vue_sample_network
  db:
    container_name: dev_rails_vue_sample_db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: >
      mysqld
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
    ports:
      - "33369:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - dev_rails_vue_sample_network

volumes:
  mysql_volume:

networks:
  dev_rails_vue_sample_network:
